name: project-voice2

services:
  voice2:
    build: 
      context: .
      dockerfile: Dockerfile
    image: project-voice2-app
    container_name: voice2-container
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - FLASK_HOST=0.0.0.0
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: always
